# Generated by Django 3.1.7 on 2021-03-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecontent',
            name='line_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
