# Generated by Django 3.1.7 on 2021-03-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='most_common_character',
            field=models.CharField(default=' ', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='line_number',
            field=models.IntegerField(unique=True),
        ),
    ]
